include:
  - compose/databases.yml
  - compose/cache.yml
  - compose/messaging.yml
  - compose/storage.yml
  - compose/email.yml
  - compose/management.yml
  - compose/proxy.yml
  - compose/backup.yml
  - compose/monitoring.yml
  - compose/ci.yml
  - compose/security.yml

networks:
  app_network:
    external: true

volumes:
  mysql_data:
  redis_data:
  mongo_data:
  redisinsight_data:
  postgres_data:
  pgadmin_data:
  rabbitmq_data:
  rabbitmq_logs:
  mailpit_data:
  minio_data:
  arcane_data:
  npm_data:
  uptime_kuma_data:
  jenkins_data:
  trivy_data:

secrets:
  db_root_password:
    file: ./secrets/db_root_password
  db_username:
    file: ./secrets/db_username
  db_password:
    file: ./secrets/db_password
  redis_password:
    file: ./secrets/redis_password
  rabbitmq_user:
    file: ./secrets/rabbitmq_user
  rabbitmq_password:
    file: ./secrets/rabbitmq_password
  pgadmin_password:
    file: ./secrets/pgadmin_password
  arcane_encryption_key:
    file: ./secrets/arcane_encryption_key
  arcane_jwt_secret:
    file: ./secrets/arcane_jwt_secret
  minio_root_user:
    file: ./secrets/minio_root_user
  minio_root_password:
    file: ./secrets/minio_root_password
