services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: jenkins-docker-proxy
    environment:
      - EVENTS=1
      - PING=1
      - VERSION=1
      - AUTH=1
      - SECRETS=0
      - POST=1
      - BUILD=1
      - COMMIT=1
      - CONFIGS=0
      - CONTAINERS=1
      - DISTRIBUTION=1
      - EXEC=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=0
      - PLUGINS=0
      - SERVICES=0
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=0
      - VOLUMES=1
      - TAGS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_network
    restart: always
    deploy:
      resources:
        limits:
          memory: 128m
          cpus: "0.1"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  jenkins:
    container_name: jenkins
    build:
      context: ../jenkins
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://jenkins-docker-proxy:2375
      - DOCKER_BUILDKIT=0
    networks:
      - app_network
    depends_on:
      - docker-socket-proxy
    restart: always
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
