services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: minimal-infrastructure-mailpit-1
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - mailpit_data:/data
    networks:
      - app_network
    restart: always
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.25"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
